### ISSUE TITLE
More efficient not to disconnect urlConnection in ElasticSearchWriter

### ISSUE THREAD

**Issue by inigo** [agido-malter/logback-elasticsearch-appender#22]
Disconnecting a urlConnection "Indicates that other requests to the server are unlikely in the near future" (from the JDK docs).

It closes the underlying socket, so it can't be reused for subsequent connections. In an app like this, where there are repeated connections to the same server, it's more efficient to keep the socket open so other urlConnections can use it. There's various discussion of this - a reasonably good article is at https://dzone.com/articles/caveats-httpurlconnection. 

This affects [ElasticsearchWriter#95 ](https://github.com/agido-malter/logback-elasticsearch-appender/blob/0a5bf697dd47d56de7bbdbc63b8a689e9caf54ec/src/main/java/com/agido/logback/elasticsearch/writer/ElasticsearchWriter.java#L95)

I've got a PR that implements this against a separate fork at https://github.com/67Bricks/logback-elasticsearch-appender/pull/2, but that may well clash with other changes that you've made, so I'll see if I can recreate it against this fork if you like?

**Comment by danslavetskiy** [comment]
Hi @inigo we also detected the same issue, PR would be appreciated :)
